spring:
  application:
    name: usercenter-service
#  sleuth:
#    trace-id128: true
#    sampler:
#      probability: 1.0
#  zipkin:
#    baseUrl: http://localhost:9411/

server:
  port: 9002

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#hystrix:
#  shareSecurityContext: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
