spring:
  application:
    name: gateway-service
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

