spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0