package com.stone.user.mapper;

import com.stone.user.model.StoneUser;
import java.util.List;

public interface StoneUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    int insert(StoneUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    StoneUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    List<StoneUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    int updateByPrimaryKey(StoneUser record);
}