package com.stone.user.mapper;

import com.stone.user.model.StoneUser;
import com.stone.user.model.StoneUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoneUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    long countByExample(StoneUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    int deleteByExample(StoneUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    int insert(StoneUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    int insertSelective(StoneUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    List<StoneUser> selectByExample(StoneUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    StoneUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") StoneUser record, @Param("example") StoneUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    int updateByExample(@Param("record") StoneUser record, @Param("example") StoneUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    int updateByPrimaryKeySelective(StoneUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone_user
     *
     * @mbg.generated Sat Oct 31 18:21:52 CST 2020
     */
    int updateByPrimaryKey(StoneUser record);
}