package com.stone.user.model;

public class StoneUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_user.id
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stone_user.user_name
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_user.id
     *
     * @return the value of stone_user.id
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_user.id
     *
     * @param id the value for stone_user.id
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stone_user.user_name
     *
     * @return the value of stone_user.user_name
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stone_user.user_name
     *
     * @param userName the value for stone_user.user_name
     *
     * @mbg.generated Sat Oct 31 18:01:33 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}